### ISSUE TITLE
Update for wrangler v3

### ISSUE THREAD

**Issue by Cherry** [cloudflare/wrangler-action#107]
This repo needs updating to wrangler v3 officially. Namely the `publish` -> `deploy` command change should be the only major thing.

It might be a good opportunity to run through all the other pending issues and PRs in this repo too for some maintenance. 👀

**Comment by JacobMGEvans** [comment]
Its going to be rewritten in TypeScript and likely the API is going to change quite a bit.

**Comment by Cherry** [comment]
> Its going to be rewritten in TypeScript and likely the API is going to change quite a bit.

Awesome! I know @demosjarco has just done [exactly that](https://github.com/demosjarco/wrangler-action-node), but maintained the API so it's a drop-in replacement. You might want to get in touch and collab with them 👀
