### ISSUE TITLE
[Question] About publish environments

### ISSUE THREAD

**Issue by eullercdr** [cloudflare/wrangler-action#116]
Hey Dears, 

I am working on a project where I need to publish the content of a website to a specific route/enviroment, for instance, "staging.meusite.com.br." However, I'm not entirely sure how to achieve this using this github action. I believe you have experience in this area, and your expertise would be immensely valuable to me.

Could you kindly guide me on how to publish a route on a worker Cloudflare in my CI GitHub repository? 

Specifically, I would like to know which parameters to pass in the action to accomplish this task successfully.

I have already set up the worker in my repository and tested it with basic functionalities, but I'm unsure about how to proceed with publishing a specific route.

Thank you for considering my request, and I look forward to your response.

**Comment by JacobMGEvans** [comment]
Greetings, 
You would define your routes in the Wrangler config (TOML or JSON) once you have that configuration file setup, [see](https://developers.cloudflare.com/workers/wrangler/configuration/#sample-wranglertoml-configuration) then you can deploy as usual and the Routes will be deployed for that Worker from the config file. You can also inline the command with `--routes`. 

If you run the action with your Wrangler config file setup for routes you can rely on its default behavior, as shown in the README.
```sh
jobs:
  deploy:
    name: Deploy
    steps:
      uses: cloudflare/wrangler-action@3.0.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
   ```
   If you want to inline it with custom scripts: 
   jobs:
  deploy:
    name: Deploy
    steps:
      uses: cloudflare/wrangler-action@3.0.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        command: deploy --route some-route
  ```

**Comment by JacobMGEvans** [comment]
Closing, assuming this answered your question. Otherwise feel free to comment again.
