### ISSUE TITLE
[v3 Follow Up] CI/CD E2E Tests

### ISSUE THREAD

**Issue by JacobMGEvans** [cloudflare/wrangler-action#117]
Depending on how we want to approach this, we could make the E2E tests more robust against flakiness and race conditions. 

1. Create separate workflows 1st one uses the Action and deploys `test-worker` the 2nd only runs on success of 1st workflow and will call the `test-worker` and check the response for a positive health check (includes the secrets) then cleans up the Workers. 

2. Similar to the first one, except its done in one workflow using Jobs

Cc: @1000hz

**Comment by demosjarco** [comment]
For this test, I think it would be a good idea to hook up GitHub's built in dependabot to watch for the `wrangler` package updates. Then on the PR that dependabot works (before merge), run these tests too to make sure this action works on the latest `wrangler` version too.
