### ISSUE TITLE
V3 missing dist?

### ISSUE THREAD

**Issue by christopherpickering** [cloudflare/wrangler-action#120]
Hi,
I've just updated to v3 and get the following error:
```
File not found: '/home/runner/work/_actions/cloudflare/wrangler-action/3.0.0/dist/index.js'
```

It seems like there should be a dist folder somewhere?

Thanks!

**Comment by JacobMGEvans** [comment]
Oh dang!

**Comment by JacobMGEvans** [comment]
Should be good now, I need to make sure the CI/CD is creating that lol Thanks for reporting!

**Comment by christopherpickering** [comment]
Thanks!

**Comment by christopherpickering** [comment]
I guess after you exclude dist from prettier your test will pass. Any chance you can do a new release, or update 3.0?

**Comment by JacobMGEvans** [comment]
I forced the `git tag` to the latest commit with the deps and built files, temp hotfix until I improve the build/release workflow.

**Comment by christopherpickering** [comment]
Works, thanks!
