### ISSUE TITLE
suggestion: tag "v3" release

### ISSUE THREAD

**Issue by randomairborne** [cloudflare/wrangler-action#134]
Manually updating github actions is a pain. [actions/upload-artifact](https://github.com/actions/upload-artifact) has a good solution in tagging the latest version as `v3`, and then updating that to new versions. Would that be considered for this repository?

**Comment by WalshyDev** [comment]
We do the same in pages-action - https://github.com/cloudflare/pages-action/blob/main/.github/workflows/publish.yml
https://github.com/cloudflare/pages-action/tags

**Comment by 1000hz** [comment]
Automation for this is now in place.
