### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by randomairborne** [cloudflare/wrangler-action#135]
on [randomairborne/speederboards actions #7](https://github.com/randomairborne/speederboard/actions/runs/5804604412/job/15734412921) I get this error when trying to use the action:
```(node:1747) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/runner/work/_actions/cloudflare/wrangler-action/3.0.1/dist/index.js:1
import { createRequire as __WEBPACK_EXTERNAL_createRequire } from "module";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47```

**Comment by itzsaga** [comment]
I'm hitting this one as well.

**Comment by JacobMGEvans** [comment]
It should be fixed now, please try again and let me know if you have any other errors surface 😄

**Comment by randomairborne** [comment]
This appears to be fixed. I will create a new error with my new error.

**Comment by itzsaga** [comment]
Confirmed it's working for me now. Thanks @JacobMGEvans!

**Comment by demosjarco** [comment]
@JacobMGEvans Another fix add on can be to add the `--target` argument on `ncc`. On my TS implementation, that fixed it for me.
Example: [demosjarco/wrangler-action-node/.github/workflows/deploy.yml#L41](https://github.com/demosjarco/wrangler-action-node/blob/main/.github/workflows/deploy.yml#L41)
Docs: [vercel/ncc#options](https://github.com/vercel/ncc#options)

Side note, but also related, you can use this to keep ECMAScript target in sync with you `tsconfig.json`. It defaults to 2015, but I see in your `tsconfig.json` you have it set to `ESNext` (which currently resolves to `ES2023`). The `ncc` argument doesn't accept a `ESNext` value, only specific years though.

**Comment by JacobMGEvans** [comment]
> @JacobMGEvans Another fix add on can be to add the `--target` argument on `ncc`. On my TS implementation, that fixed it for me.
> Example: [demosjarco/wrangler-action-node/.github/workflows/deploy.yml#L41](https://github.com/demosjarco/wrangler-action-node/blob/main/.github/workflows/deploy.yml#L41)
> Docs: [vercel/ncc#options](https://github.com/vercel/ncc#options)
> 
> Side note, but also related, you can use this to keep ECMAScript target in sync with you `tsconfig.json`. It defaults to 2015, but I see in your `tsconfig.json` you have it set to `ESNext` (which currently resolves to `ES2023`). The `ncc` argument doesn't accept a `ESNext` value, only specific years though.

Hey thanks that's huge help! I will try these out 😁
