### ISSUE TITLE
Enable users to depend on @3 rather than pinned @3.0.0 version

### ISSUE THREAD

**Issue by IgorMinar** [cloudflare/wrangler-action#144]
Our readme.md currently instructs users to specify full version number when installing the action:
```
      - name: Deploy
        uses: cloudflare/wrangler-action@3.0.0
```

This means that they will forever be pinned to 3.0.0. Could we instead enable users to specify the dependency as `cloudflare/wrangler-action@3` as is common in npm?

I believe this will require us to maintain and overwrite the `3` tag with every minor and patch release, similarly how actions/checkout does it: https://github.com/actions/checkout/tags (they use `v` prefix, so see the `v3` tag).

**Comment by JacobMGEvans** [comment]
This is already possible & additionally added it to the docs https://github.com/cloudflare/wrangler-action#big-changes-in-v3

This was enabled by With these 2 PRs in for automating
This one for build & tagging for release:
https://github.com/cloudflare/wrangler-action/pull/128

This one for automating the release & changelog
https://github.com/cloudflare/wrangler-action/pull/132

**Comment by IgorMinar** [comment]
awesome! 🎉  Thank you
