### ISSUE TITLE
v3 does not work with other package managers

### ISSUE THREAD

**Issue by zanechua** [cloudflare/wrangler-action#156]
Currently getting the following error thrown ` npm ERR! Cannot read properties of null (reading 'matches')` in [https://github.com/zanechua/comment-worker/actions/runs/5857501953/job/15879483256 ](https://github.com/zanechua/comment-worker/actions/runs/5857501953/job/15879483256 )

Seems to be an [incompatibility](https://github.com/npm/cli/issues/4367#issuecomment-1674381286) since I am using `pnpm` instead of `npm`?

Can we have support for making use of other package managers to install wrangler other than `npm` ?

**Comment by dotansimha** [comment]
Same here, since upgraded to v3 of the action, the deploy action fails with:

```
📥 Installing Wrangler
  Running command: npm install wrangler@3.4.0
  npm ERR! Cannot read properties of null (reading 'matches')
```

**Comment by JacobMGEvans** [comment]
Hmm, I can look into making it package agnostic and fallback to npm or pnpm (honestly I prefer pnpm myself too lol)

**Comment by beary** [comment]
I deployed successfully without wrangler-action, this is my config. You can install wrangler on your deploy step or add it into you package.json.
```yaml
      - name: Deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN}}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID}}
        run: |
          pnpm install --save-dev wrangler
          pnpm exec wrangler pages deploy public --project-name=<Your project name>
```

**Comment by AdiRishi** [comment]
Just ran into this myself. With the current state of `wrangler-action` you basically can't use pnpm in CI. Got the same exception
```
📥 Installing Wrangler
  Running command: npm install wrangler@latest
  npm ERR! Cannot read properties of null (reading 'matches')
  
  npm ERR! A complete log of this run can be found in: /home/runner/.npm/_logs/2023-08-29T05_44_20_839Z-debug-0.log
  Error: 🚨 Action failed
```
It's worth noting that it works fine with yarn v3. Discovered this bug as I moved to pnpm.

**Comment by AdiRishi** [comment]
@JacobMGEvans this may not be resolved.

Just tied to test the fix by using `uses: cloudflare/wrangler-action@main` and got the following output
```sh
Run cloudflare/wrangler-action@main
  with:
    accountId: ***
    apiToken: ***
    wranglerVersion: latest
    preCommands: echo "*** pre commands ***"
wrangler r2 bucket create turborepo-cache || true
  echo "******"
  
    command: deploy
    quiet: false
  env:
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
Error: File not found: '/home/runner/work/_actions/cloudflare/wrangler-action/main/dist/index.mjs'
```
Looks like it's able to detect pnpm but there is some bug with executing index.mjs? Here is the link to the [failing action](https://github.com/AdiRishi/turborepo-remote-cache-cloudflare/actions/runs/6254980601/job/16983539918?pr=92) in case that helps.

**Comment by JacobMGEvans** [comment]
I'm pretty sure I haven't released this fix yet.

**Comment by AdiRishi** [comment]
> I'm pretty sure I haven't released this fix yet.

Hmm my apologies then. I assumed #166 was the complete fix. I was able to access it given that it's already on the main branch.

**Comment by nix6839** [comment]
> I was able to use by using the @main tag on wrangler-action.

`main` branch doesn't have `/dist/index.mjs`. It's a output of a build.

**Comment by AdiRishi** [comment]
> > I was able to use by using the @main tag on wrangler-action.
> 
> `main` branch doesn't have `/dist/index.mjs`. It's a output of a build.

Right, that makes sense! My bad 😅

**Comment by hubertott** [comment]
Just an FYI I just got this on my recent deployment and noticed this work was just merged into release `v3.2.0` 

> file:///home/runner/work/_actions/cloudflare/wrangler-action/v3/dist/index.mjs:2923
    throw new Error("Package manager is not detected");
          ^

> Error: Package manager is not detected
    at realPackageManager (file:///home/runner/work/_actions/cloudflare/wrangler-action/v3/dist/index.mjs:2923:11)
    at file:///home/runner/work/_actions/cloudflare/wrangler-action/v3/dist/index.mjs:2925:48
    at file:///home/runner/work/_actions/cloudflare/wrangler-action/v3/dist/index.mjs:31[17](https://github.com/kmddev/pwa-magento2/actions/runs/6383693316/job/17324926522#step:8:18):3
    at ModuleJob.run (node:internal/modules/esm/module_job:[19](https://github.com/kmddev/pwa-magento2/actions/runs/6383693316/job/17324926522#step:8:20)2:25)
    at async DefaultModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async loadESM (node:internal/process/esm_loader:40:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

> Node.js v[20](https://github.com/kmddev/pwa-magento2/actions/runs/6383693316/job/17324926522#step:8:21).5.0

**Comment by nix6839** [comment]
> Just an FYI I just got this on my recent deployment and noticed this work was just merged into release v3.2.0

@hubertott  Please try the following
```yml
- uses: cloudflare/wrangler-action@v3
  with:
    packageManager: "npm" # change npm to yarn or pnpm
```

**Comment by hubertott** [comment]
@nix6839 thanks for that.

Maybe I am blind, but there doesn't appear to be any reference to this in the README.
Should this not be considered a breaking change?

**Comment by nix6839** [comment]
Sorry, I didn't document when I contributed.
I'm not a native english speaker, so it would be great if someone who speaks English better than me could contribute.

A short description of the feature:
- Read the packageManager settings. If it's one of npm, yarn, or pnpm, use it.
- If the packageManager is not set or is invalid, find package-lock.json or yarn.lock or pnpm-lock.yaml in `workingDirectory`, and use the package manager for it.
- If all of the above steps fail, throw error.
