### ISSUE TITLE
Cloudflare Pages Rollback

### ISSUE THREAD

**Issue by lucasfreyptml** [cloudflare/wrangler-action#176]
Hi team,

Is Cloudflare Pages Rollback supported on this actions ? If not is it in the current stream of work ?

Cheers

**Comment by admah** [comment]
This action is limited to current Wrangler functionality, and Pages rollbacks are not part of that currently. While that may change in the future, I can't speak to a timeline or estimate on it.

**Comment by 1000hz** [comment]
Closing this as it's really a feature request for wrangler itself rather than functionality we'd add to wrangler-action. Feel free to reopen as a feature request in https://github.com/cloudflare/workers-sdk.
