### ISSUE TITLE
Add outputs to action

### ISSUE THREAD

**Issue by 1000hz** [cloudflare/wrangler-action#211]
As requested in #210, it would be useful for this action to provide some [outputs](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs-for-docker-container-and-javascript-actions) to allow users to consume the results of the action run in subsequent workflow steps.

For the MVP, we could start with providing a `command-output` that makes the stdout from executing `command` available. We could also possibly try to detect if a workers or pages deployment was made and provide a `deployment-url` we infer from the output.

**Comment by admah** [comment]
Would solving [this issue](https://github.com/cloudflare/workers-sdk/issues/2012) help with this?
