### ISSUE TITLE
Error:  bucket directory "./public" does not exist

### ISSUE THREAD

**Issue by yet-another-dev** [cloudflare/wrangler-action#22]
Trying to get this to work for a Workers Site. The built directory for my site is `repo-root/project-root/public/`. The problem could be related to my Workers Site being in a subdirectory.

**Comment by ashleymichal** [comment]
@yet-another-dev it may require clarification in docs, but in general `site.bucket` should be the relative path from the directory containing the wrangler.toml to the bucket directory.

**Comment by yet-another-dev** [comment]
Thanks for specifying that, @ashleymichal. Yes, pretty sure I've got this part right. 

Building and deploying locally works fine, it's only in the context of GitHub actions that it fails (with the above error, saying that the bucket directory doesn't exist). I've defined `workingDirectory` specifying the subdirectory. My `wrangler.toml` is in that directory. Not sure how to trouble shoot further.

**Comment by ashleymichal** [comment]
hmm. without inspecting the repo and the action this will be hard to diagnose.

**Comment by signalnerve** [comment]
@yet-another-dev a link to a repo/action would be awesome if you can provide it!

**Comment by yet-another-dev** [comment]
Turns out I had a stray `- uses: actions/checkout@master` before my deploy step in my GitHub action yaml file. My repo's master branch doesn't yet have the directory structure I'm using on my development branch, hence the error. 🤦 

Sorry for the noise (and thanks for the great work)!
