### ISSUE TITLE
confusion re usage

### ISSUE THREAD

**Issue by bkyerv** [cloudflare/wrangler-action#223]
![Screenshot 2023-12-26 at 14 19 52](https://github.com/cloudflare/wrangler-action/assets/87478959/1e34ca8b-0c2e-45d7-85a9-05778823e516)

in the Big changes in v3 it says global api key is not support

in the Usage section it says:
```
    with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
```

what api key are we expected to pass?

**Comment by Cherry** [comment]
You'll need to use an API token:

https://developers.cloudflare.com/workers/wrangler/ci-cd/#api-token
