### ISSUE TITLE
(enhancement): Surface inner exception when uploading secrets fails

### ISSUE THREAD

**Issue by AdiRishi** [cloudflare/wrangler-action#226]
There has been some scattered discussion on this in other issues but I'm making a seperate issue here as I plan on making a PR for this.

Currently, whenever there is an error uploading secrets, the `wrangler-action` shows `Failed to upload secrets.` but provides no additional context.
![Screenshot 2024-01-02 at 2 56 08 pm](https://github.com/cloudflare/wrangler-action/assets/8351234/997f9a81-9875-4295-844f-66edbe0cefe3)

This makes it very very difficult to debug and have any idea on why the secret upload failed.

**Comment by AdiRishi** [comment]
@vladinator1000 yes I solved my issue. The PR I made that was merged will show additional information when you run the action in debug mode on GitHub. You can enable debug mode when trying to re-run a failed job.
![Screenshot 2024-03-05 at 9 38 41 am](https://github.com/cloudflare/wrangler-action/assets/8351234/8830c5fd-558f-4091-9306-41086fead9ac)

In my case, I was passing an invalid `wranglerVersion`, and the debug log showed the following
```
🔑 Uploading secrets...
  Error: Invalid Version: latest
  ##[debug]TypeError: Invalid Version: latest
  ##[debug]    at new SemVer (file:///home/runner/work/_actions/cloudflare/wrangler-action/v3/dist/index.mjs:3094:13)
  ##[debug]    at compare (file:///home/runner/work/_actions/cloudflare/wrangler-action/v3/dist/index.mjs:3368:32)
  ##[debug]    at gt (file:///home/runner/work/_actions/cloudflare/wrangler-action/v3/dist/index.mjs:3379:29)
  ##[debug]    at semverCompare (file:///home/runner/work/_actions/cloudflare/wrangler-action/v3/dist/index.mjs:28453:24)
  ##[debug]    at uploadSecrets (file:///home/runner/work/_actions/cloudflare/wrangler-action/v3/dist/index.mjs:28653:13)
  ##[debug]    at main (file:///home/runner/work/_actions/cloudflare/wrangler-action/v3/dist/index.mjs:28561:15)
  ::endgroup::
Error: Failed to upload secrets.
Error: 🚨 Action failed
```

**Comment by vladinator1000** [comment]
Gotcha @AdiRishi, I tried running it in debug mode, but didn't see any extra information. It seems like a separate problem so I created a new issue https://github.com/cloudflare/wrangler-action/issues/240
