### ISSUE TITLE
Wrangler is trash

### ISSUE THREAD

**Issue by erikonad** [cloudflare/wrangler-action#253]
- Slow and buggy
- No support for bulk deployments
- Caches things into node_modules/.wrangler that causes bugs

This is one of the lowest quality software I've ever had the displeasure to use. Just make things like "pages deploy" work over HTTP and I would much rather use that than ever have to deal with wrangler again.

**Comment by penalosa** [comment]
I'm going to close this for now, since it's relatively broad. Could you open specific issues on the workers-sdk repo if there are improvements you'd like to see?
