### ISSUE TITLE
Lack of `accountId` leaks account names and IDs in the logs

### ISSUE THREAD

**Issue by arunsathiya** [cloudflare/wrangler-action#288]
When I don't supply the `accountId` param, the wrangler action logs contain the list of all account names and account IDs, along with a `More than one account available but unable to select on` message. 

I am not sure if account IDs are considered sensitive information by Cloudflare, by if they are, there's value in masking them in the logs.

**Comment by arunsathiya** [comment]
Should I file this on [the Workers SDK tracker](https://github.com/cloudflare/workers-sdk/issues) instead?

**Comment by shahsimpson** [comment]
Cloudflare doesn't consider the account ID sensitive
