### ISSUE TITLE
Cache install?

### ISSUE THREAD

**Issue by till** [cloudflare/wrangler-action#29]
Something I noticed, every time I used this action, it had to do `npm install` and download the rust binary.

It would be nice and more dockerish (I believe) if those came in the action pre-installed. Reproducible dependencies also make developer life happier. Whatever runs locally, works online — given the same tags and versions.

And then I can update by using a different release of the action, or something like a `latest` tag if I always want the latest and greatest.

Thoughts?

**Comment by pepijn-vanvlaanderen** [comment]
+1
