### ISSUE TITLE
[pages-action migration] Add Support for Deployments Feature 

### ISSUE THREAD

**Issue by aninibread** [cloudflare/wrangler-action#301]
**Context:** With the deprecation of [`pages-action`](https://github.com/cloudflare/pages-action), we are encouraging users who relied on it for Pages project deployments to migrate to `wrangler-action`.

**Problem:** We recognize that `wrangler-action` currently does not include the "Deployments" feature available in `pages-action`. We are actively working to add this feature to `wrangler-action` to align with `pages-action` capabilities and ensure users have the visibility and control they need when managing their deployments.

Please follow this issue for updates as we progress. We also welcome your feedback. If there are other deployment-related features or improvements you'd like to see, please share your suggestions here.

**From:** Cloudflare Workers Team

**Comment by sebdanielsson** [comment]
Waiting for the next ansible-core release. Probably 2.18.1.

**Comment by dargmuesli** [comment]
Maybe the README in https://github.com/cloudflare/pages-action can be updated to not point to this issue anymore (would require a short un-archival to push the change).
