### ISSUE TITLE
Wragler action 3.12 returns incorrect deployment URL

### ISSUE THREAD

**Issue by Pante** [cloudflare/wrangler-action#317]
I have the following workflow which deploys two related projects to separate domains before subsequently posting the latter project's URL on a GitHub comment, https://github.com/forus-labs/forui/actions/runs/11682147658/workflow?pr=174#L75.

After 3.12 was released, we noticed that the URL being posted was incorrect. Instead of posting the latter project's URL, it posted the first project's. It seems like the `deployment-url` isn't being updated after the action is called the for the first time.

Incorrect URL using 3.12: https://github.com/forus-labs/forui/pull/174#issuecomment-2432064082

Correct URL after reverting to 3.11: https://github.com/forus-labs/forui/pull/254#issuecomment-2454071044

**Comment by Maximo-Guk** [comment]
Hi @Pante , can you confirm that `3.12.1` release fixed this for you?

**Comment by Pante** [comment]
Seems to be working now. Thanks for the quick fix!
