### ISSUE TITLE
Cache wrangler installation

### ISSUE THREAD

**Issue by SukkaW** [cloudflare/wrangler-action#323]
I have separate actions (`Build`, `Deploy to Cloudflare Pages`, and `Deploy to somewhere else`), which means `cloudflare/wrangler-action` won't be run within the `Build` action. So I always ended up installing `wrangler` every time:

https://github.com/cloudflare/wrangler-action/blob/6c6d3321efd4e3f0c0b7037ff33ce2feddc7a8b4/src/index.ts#L154

Is it possible to cache the installation of `wrangler`? Or are there any instructions on how I can do this manually (e.g. where will be wrangler be installed so I can manually add cache)?

**Comment by shahsimpson** [comment]
Hi! You can cache npm store directory with this action, which will use your locally installed wrangler version
https://github.com/actions/cache

**Comment by thelinuxlich** [comment]
Was anyone able to cache wrangler using pnpm?

**Comment by SukkaW** [comment]
> Was anyone able to cache Wrangler using pnpm?

That won't be easy since pnpm uses a global store (for later symlink into `node_modules`).

It is a shame that Cloudflare doesn't provide a standalone `wrangler` binary and use that in the GitHub Actions.

**Comment by dukeflyheli** [comment]
here is an example of how to cache wrangler 

https://gist.github.com/dukeflyheli/e75cb08a17a01b71cfa91af8a7231562

**Comment by ulgens** [comment]
The action doesn't cache the installation by default and doesn't give an option to enable caching. The readme doesn't mention caching either. I think the issue should stay open.
