### ISSUE TITLE
Worker deployment authentication error

### ISSUE THREAD

**Issue by Beingbook** [cloudflare/wrangler-action#33]
every wrangler action fails with:
```
Built successfully, built project size is 189 KiB.
Error:  Code 10000: Authentication error
```

I tried both worker api token which built with template for worker and global API key and email to publish worker but two method results are same.
Is there any debug log options? and actually deployments get success.
Actually it happens also in local environment. If there's need more information, let me know.

**Comment by Beingbook** [comment]
And I verified the token with:
```
curl -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" \ 
     -H "Authorization: Bearer SECRET_TOKEN" \
     -H "Content-Type:application/json"
```

the result:
```
{"result":{"id":"...","status":"active"},"success":true,"errors":[],"messages":[{"code":10000,"message":"This API Token is valid and active","type":null}]}%    
```

I think wrangler identify something wrong... CF worker is awesome but it's an obstacle.

**Comment by mroderick** [comment]
I ran into to something similar, which was clearly an error on my end.

The token I was trying to use was configured to work on a different site than what was configured in `wrangler.toml`. That gave me exactly the `Error:  Code 10000: Authentication error` error message that @Beingbook saw.

Once I'd fixed my mistake, and created a token for the actual site I was trying to publish to, it worked just fine.

**Comment by Beingbook** [comment]
@mroderick thank you
