### ISSUE TITLE
Publish worker secrets before publish worker

### ISSUE THREAD

**Issue by bradyjoslin** [cloudflare/wrangler-action#34]
The wrangler action errors when publishing a secret for the first time if that secret hasn't been previously published to the targeted environment manually. The action fails with an error saying that the new secret variable in the worker is undefined.

This could be fixed by modifying the order in which the action script publishes the worker and secret.  Currently the worker is published before the secret, propose changing to publishing secrets before the worker.

[Current code](https://github.com/cloudflare/wrangler-action/blob/6531840e6e51bef0e787759fa4ddd2fee4cf2525/entrypoint.sh#L66)

```bash
# If an environment is detected as input, for each secret specified get the value of
# the matching named environment variable then configure using wrangler secret put.
if [ -z "$INPUT_ENVIRONMENT" ]
then
  wrangler publish

  for SECRET in $INPUT_SECRETS; do
    VALUE=$(printenv "$SECRET") || secret_not_found "$SECRET"
    echo "$VALUE" | wrangler secret put "$SECRET"
  done
else
  wrangler publish -e "$INPUT_ENVIRONMENT"

  for SECRET in $INPUT_SECRETS; do
    VALUE=$(printenv "$SECRET") || secret_not_found "$SECRET"
    echo "$VALUE" | wrangler secret put "$SECRET" --env "$INPUT_ENVIRONMENT"
  done
fi
```

Proposed:

```bash
# If an environment is detected as input, for each secret specified get the value of
# the matching named environment variable then configure using wrangler secret put.
if [ -z "$INPUT_ENVIRONMENT" ]
then
  for SECRET in $INPUT_SECRETS; do
    VALUE=$(printenv "$SECRET") || secret_not_found "$SECRET"
    echo "$VALUE" | wrangler secret put "$SECRET"
  done

  wrangler publish
else
  for SECRET in $INPUT_SECRETS; do
    VALUE=$(printenv "$SECRET") || secret_not_found "$SECRET"
    echo "$VALUE" | wrangler secret put "$SECRET" --env "$INPUT_ENVIRONMENT"
  done

  wrangler publish -e "$INPUT_ENVIRONMENT"
fi
```

**Comment by bradyjoslin** [comment]
Looks like this wrangler issue has to be resolved first to allow `secret put` before initial `publish`.
https://github.com/cloudflare/wrangler/issues/1418

**Comment by sanjeev2981** [comment]
I'm also running into this issue.  Suggested fix was to push a hello world worker to the route and then have the workflow overwrite the existing contents in subsequent pushes.

**Comment by bradyjoslin** [comment]
No longer a problem when following the advice that closed the related wrangler issue.  https://github.com/cloudflare/wrangler/issues/1418#issuecomment-732761146

**Comment by bradyjoslin** [comment]
Actually, after testing further, the Action does have to be re-run after the first deploy to avoid the worker giving an error.  Changing the order of Action to put the secret before deploying the worker appears to remain needed.

**Comment by grahamlyons** [comment]
I'm running into the same problem. If I add a secret in the pipeline then the deployment fails because the variable in the code isn't defined anywhere.

Is the logic put that way round because a new worker can't have a secret added to it before it's published?
