### ISSUE TITLE
Token authentication is unusable as written in README

### ISSUE THREAD

**Issue by seanmorris** [cloudflare/wrangler-action#36]
The secret seems to need the be named `CLOUDFLARE_API_TOKEN`. This works fine.

Does not works as specified in README: `CF_API_TOKEN`.

Using cloudflare/wrangler-action@1.2.0

**Comment by signalnerve** [comment]
hey @seanmorris, very interesting! i checked in with the wrangler team and we haven't recently changed any of the environment variable names, so it should still be using `CF_API_TOKEN`. 

just as a heads-up, it's possible that your GitHub secret may be called `CLOUDFLARE_API_TOKEN` inside of your repo settings. in the config for the GitHub actions workflow, the only particular part about the naming is the _key_ part - it should be called `apiToken`, as below:

```yaml
with:
  apiToken: ${{ secrets.CF_API_TOKEN }}
```

the secrets bit, that is, `secrets.CF_API_TOKEN`, can actually be called whatever value you'd like! if you named it `CLOUDFLARE_API_TOKEN` when you configured the secret value in your repo, that's totally okay as well.

closing this as i think this is a slight config issue, let me know if you aren't able to fix!
