### ISSUE TITLE
Suggestion: Remove recommendation for `repository_dispatch` in favor of `workflow_dispatch`

### ISSUE THREAD

**Issue by Indigenuity** [cloudflare/wrangler-action#40]
A couple months ago, GHA [announced](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/) the `workflow_dispatch` event. This new event treats manually triggered workflows as first-class citizens.  It can be triggered via the UI, eliminating the requirement for cumbersome CLI commands that `repository_dispatch` requires.  

Now, it's not this repo's responsibility for showing people the ropes around GHA, but as long as it is in the business of making recommendations in the README, this'd be a nice update to make.

Happy to make a PR for it if people think the change would be useful

**Comment by signalnerve** [comment]
ah, awesome! That totally makes sense 👍  I'd love to merge in a PR if you're interested in updating the README

**Comment by dalbitresb12** [comment]
@signalnerve Shouldn't this issue be closed since #42 was merged?

**Comment by signalnerve** [comment]
> @signalnerve Shouldn't this issue be closed since #42 was merged?

yep thanks!
