### ISSUE TITLE
Use variables for environment

### ISSUE THREAD

**Issue by smalomo** [cloudflare/wrangler-action#41]
If this is already possible, I haven't been able to figure out the correct syntax. What I'm trying to do is pass in the name of the branch that triggered the workflow as the environment (e.g. if this was triggered from a commit to `staging` then pass in `staging` as the environment). I've tried the following (both with and without quotes):

```- name: Publish
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: '${GITHUB_REF##*/}' 
```

but the publish action fails with `Error:  Could not find environment with name "${GITHUB_REF##*/}"`

Is there a way to dynamically publish to different environments?

**Comment by jasikpark** [comment]
Would it not be `${{ GITHUB_REF }}` like `${{ secrets.CF_API_TOKEN }}` (two `{{`'s)?

**Comment by Scooletz** [comment]
It works in my case

```
        environment: ${{ env.deployment }}
```
