### ISSUE TITLE
"builder error: failed to parse header value"

### ISSUE THREAD

**Issue by winstonwolff** [cloudflare/wrangler-action#47]
I'm trying to use this Wrangler publish action, but my script fails with:
  "Error: Error: builder error: failed to parse header value"

Attached is a screenshot. Perhaps the error is some configuration error in my wrangler.toml, but it works on my dev box. Is there some way to trace where this error is coming from and at what step?
![Screen Shot 2020-12-07 at 5 57 43 PM](https://user-images.githubusercontent.com/281580/101428658-04c2a300-38b6-11eb-80d5-71fb607f4c2d.png)

**Comment by signalnerve** [comment]
Interesting! Haven't seen this before. Can you share your GitHub repo here?

**Comment by winstonwolff** [comment]
The repo is a private one for my client, so I cannot share it. But I get the same failure if I put a 'wrangler whoami' in the pre-command. I wonder if I have missed a step where wrangler knows my cloudflare credentials?

**Comment by winstonwolff** [comment]
!!! wrangler whoami
stack backtrace:
Error:  Error: builder error: failed to parse header value
   0: failure::backtrace::internal::InternalBacktrace::new
   1: <failure::backtrace::Backtrace as core::default::Default>::default
   2: wrangler::commands::whoami::whoami
   3: wrangler::run
   4: wrangler::main
   5: std::sys_common::backtrace::__rust_begin_short_backtrace
   6: std::rt::lang_start::{{closure}}
   7: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:373:40
      std::panicking::try
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:337:19
      std::panic::catch_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:379:14
      std::rt::lang_start_internal
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/rt.rs:51:25
   8: main

**Comment by winstonwolff** [comment]
If I set `RUST_BACKTRACE=1`
and then run `wrangler whoami`
I get this:
```
 stack backtrace:
Error:  Error: builder error: failed to parse header value
   0: failure::backtrace::internal::InternalBacktrace::new
   1: <failure::backtrace::Backtrace as core::default::Default>::default
   2: wrangler::commands::whoami::whoami
   3: wrangler::run
   4: wrangler::main
   5: std::sys_common::backtrace::__rust_begin_short_backtrace
   6: std::rt::lang_start::{{closure}}
   7: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:373:40
      std::panicking::try
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:337:19
      std::panic::catch_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:379:14
      std::rt::lang_start_internal
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/rt.rs:51:25
   8: main
```

**Comment by winstonwolff** [comment]
It was my API token. My problem is fixed.

But a feature request would be a better error message for this case.

**Comment by signalnerve** [comment]
g2k and glad you got it working! can you file a ticket in https://github.com/cloudflare/wrangler for this?
