### ISSUE TITLE
Option to use a difrerent config file

### ISSUE THREAD

**Issue by Moser-ss** [cloudflare/wrangler-action#62]
The wrangler CLI allows publishing using a different config file. It will be nice to have that option

**Comment by cowchimp** [comment]
It's marked as completed but I don't understand how to configure this.
@JacobMGEvans I see you marked it as completed. Can you please share how it's achievable?

**Comment by JacobMGEvans** [comment]
One of the Cloudflare engineers working on it may be able to help you, I also unfortunately don't remember 4 yrs ago

**Comment by pehtoorismies** [comment]
@cowchimp any luck with the configuration? It seems that this can't be configured, just eyeballed the source.
