### ISSUE TITLE
Run without authentication

### ISSUE THREAD

**Issue by hazcod** [cloudflare/wrangler-action#64]
Hi, is it possible to run `wranger build` using this action without authentication?
`wrangler` will often run as a build step in GitHub Actions, and if this is triggered by e.g. dependabot secrets will not be filled in.

**Comment by ffflabs** [comment]
you could keep a `wrangler.example.toml` under version control, holding a few dummy values that are enough to build and perhaps test the bundle. 

In your workflow you'd just need to rename it as `wrangler.toml` before moving to the next step.

**Comment by hazcod** [comment]
@ffflabs can you elaborate? That would still require credentials I think?

**Comment by hazcod** [comment]
For ref, my Actions fail when they are opened by dependabot since they don't have a token.
https://github.com/iron-security/documentation/runs/5779968918?check_suite_focus=true

**Comment by hazcod** [comment]
@JacobMGEvans was this fixed or?

**Comment by JacobMGEvans** [comment]
So you should be able to do that now, I think this is what you are referring to: 
https://github.com/cloudflare/wrangler-action/blob/e18e1dfc82c248a074fe377c10d081fea2beb1d1/.github/workflows/deploy.yml#L35C6-L42C1

**Comment by hazcod** [comment]
Doesn't seem so: https://github.com/iron-security/website/actions/runs/5790001644/job/15692197407?pr=67

**Comment by JacobMGEvans** [comment]
I'll take another look 😊

**Comment by 1000hz** [comment]
Closing this as it's really a feature request for `wrangler` itself rather than functionality we'd add to `wrangler-action`. Feel free to reopen as a feature request in https://github.com/cloudflare/workers-sdk
