### ISSUE TITLE
Feature: run Action to deploy temporary pull request environments

### ISSUE THREAD

**Issue by hazcod** [cloudflare/wrangler-action#65]
Would be awesome to be able to deploy to Pages and destroy after a PR merges.

**Comment by hazcod** [comment]
@JacobMGEvans was this implemented?

**Comment by JacobMGEvans** [comment]
No, but I like the idea!

**Comment by WalshyDev** [comment]
Hey,

You could implement yourself today with the [pages-action](https://github.com/cloudflare/pages-action/#outputs) we provide outputs where you can grab the deployment ID and store it somewhere to then call DELETE on [pull_request.closed](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request)

I've made a ticket for us as well to track this for Pages using our Git integration.

Thanks for the suggestion!
