### ISSUE TITLE
Error: Your provided upload_dir /github/workspace/workers/dist does not exist.

### ISSUE THREAD

**Issue by willin** [cloudflare/wrangler-action#67]
https://github.com/willin/willin.wang/runs/5049488142?check_suite_focus=true

however, workers dir is just `workers/` not `workers/dist`

is there a config key to set?

**Comment by chientrm** [comment]
Same error

**Comment by BogdanMaier** [comment]
Same here, with no real progress after a debug session while trying to figure out if there an workaround around the progress.

**Comment by hood** [comment]
Any news on this?

**Comment by tibotiber** [comment]
@hood have you tried providing the directory in your command with `pages publish dist --project-name=my-project`?

for others, the logs are not available in the link provided, it's too old.
