### ISSUE TITLE
[docs] broken url

### ISSUE THREAD

**Issue by lookfirst** [cloudflare/wrangler-action#70]
![image](https://user-images.githubusercontent.com/85355/158080886-4f44e40d-1c5c-4469-bc44-9ff7b69a8f10.png)

**Comment by lookfirst** [comment]
![image](https://user-images.githubusercontent.com/85355/158080910-b0120481-30aa-4a88-a962-05779c8bd65c.png)

**Comment by lookfirst** [comment]
Sidenote: It would be good to add some documentation about exactly what permissions are required. Just using a template is kind of a weak answer since it seems to add all sorts of stuff.

**Comment by lookfirst** [comment]
sweet, thanks @JacobMGEvans

**Comment by JacobMGEvans** [comment]
Doing an overhaul of the CI/CD section of Cloudflare Docs, this will include Wrangler Action README mostly being reworked and moved over, and referenced in here.
