### ISSUE TITLE
The build is broken

### ISSUE THREAD

**Issue by lookfirst** [cloudflare/wrangler-action#78]
https://github.com/cloudflare/wrangler-action/actions/runs/2294220847

**Comment by gagan-suie** [comment]
The logs in your workflow seem to have expired.

**Comment by lookfirst** [comment]
Nobody has built the action in 4+ months. https://github.com/cloudflare/wrangler-action/actions

**Comment by gagan-suie** [comment]
sorry i didn't look at the url properly. i thought it was your own project's workflow.

**Comment by lookfirst** [comment]
![doh](https://media.giphy.com/media/yvBAuESRTsETqNFlEl/giphy.gif)

**Comment by lookfirst** [comment]
looks great, nice work @JacobMGEvans
