### ISSUE TITLE
Deployment breaks if not specifying wrangler version

### ISSUE THREAD

**Issue by liorgross** [cloudflare/wrangler-action#88]
Git action will fail without reason or information if "wranglerVersion" is not present in "main.yml" file, and will only work with version 2.0.0. If I specify any other version - it breaks:

![Screen Shot 2022-10-07 at 12 52 33 PM](https://user-images.githubusercontent.com/5938524/194620925-30c20ddd-83b5-43a6-9360-c299a6b5f78a.png)
![Screen Shot 2022-10-07 at 12 53 06 PM](https://user-images.githubusercontent.com/5938524/194620928-13b0d803-5d79-4d44-9a66-e7be89af7941.png)

Only when specifying version 2.0.0 it works:
![Screen Shot 2022-10-07 at 1 01 54 PM](https://user-images.githubusercontent.com/5938524/194621113-fbba91b5-a790-445b-bc5c-008a076c505f.png)

**Comment by teaglebuilt** [comment]
I can confirm this as well
