### ISSUE TITLE
Use of github actor instead of email account on API issued Key

### ISSUE THREAD

**Issue by mateenis** [cloudflare/wrangler-action#93]
Hi,

In our organization, there are multiple people using the action to deploy workers from this action, but somehow for all deployments it shows my email address like "[9870d6cd] via Wrangler by my@email.com"

I want it to show the name of github.actor whoever is running the action.

Can you help? Or suggest how to go about it.

**Comment by JacobMGEvans** [comment]
Sorry for the late response, were you able to get this figured out? 

In the future too we have a great community on Discord for such questions https://discord.com/invite/CloudflareDev
