### ISSUE TITLE
Documentation now out of date.

### ISSUE THREAD

**Issue by andykillen** [cloudflare/wrangler-action#94]
Would have forked and done a PR but there is no way. 

1. 
**runs-on: ubuntu-latest** 
should be changed to be
**runs-on: ubuntu-22.04**

2. 
**- uses: actions/checkout@v2**
should be changed to be
**- uses: actions/checkout@v3**

**Comment by penalosa** [comment]
Hi! Thanks for reporting this. Are you running into issues with `ubuntu-latest`? As far as I know, GitHub should be switching over `ubuntu-latest` to 22 fairly soon anyway
