### ISSUE TITLE
Interest in rewriting in typescript

### ISSUE THREAD

**Issue by Cyb3r-Jak3** [cloudflare/wrangler-action#95]
I was wondering if there was any interest in rewriting this action to be a [JavaScript](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action) one over being run in a docker container? It means that users would have an easier time with integrating as they wouldn't need to use the `pre` or `post` commands section. 

For reference, I wrote my own [wrangler action](https://github.com/Cyb3r-Jak3/wrangler-action) that used typescript/javascript, and I am willing to put in the work to port it over, but I didn't want to start if this is something that isn't desired.

**Comment by JacobMGEvans** [comment]
Funny you ask, I plan on doing this. There will be some internal discussions necessary and technical specs, I appreciate the interest though and once I have a PR and public Spec I will be sure to get you looped in!

**Comment by Cyb3r-Jak3** [comment]
Sounds good!
